apiVersion: apps/v1
kind: Deployment
metadata:
  name: pronestheus
  labels:
{{- include "default.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pronestheus
  template:
    metadata:
      labels:
        app: pronestheus
    spec:
      serviceAccountName: pronestheus-service-account
      containers:
        - name: pronestheus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "--listen-addr"
            - "0.0.0.0:{{ .Values.service.port }}"
            - "--nest-api-url"
            - {{ .Values.nest.url | quote}}
            - "--nest-api-token"
            - {{ .Values.nest.token | quote}}
            - "--weather-api-url"
            - {{ .Values.openWeatherMap.url | quote}}
            - "--weather-api-location-id"
            - {{ .Values.openWeatherMap.location | quote}}
            - "--weather-api-token"
            - {{ .Values.openWeatherMap.token | quote}}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
      imagePullSecrets:
        - name: pronestheus-registry-secret
